name: 'ssh-tool'
description: 'ssh commond & scp files'
author: 'kevin'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'server'
  color: 'white'

# Define your inputs here.
inputs:
  host:
    description: 'Hostname or IP address of the server'
    required: true
  port:
    description: 'Port number of the server.'
  username:
    description: 'Username for authentication. eg: root'
    required: true
  password:
    description: 'Password for password-based user authentication.'
  privateKey:
    description:
      'private key for either key-based or hostbased user authentication
      (OpenSSH format). '
  command:
    description:
      'The shell command you want to execute. Multiple commands are separated by
      newlines. '
  sourceFiles:
    description: 'Source files to be transferred'
  targetDir:
    description: 'Destination folder for file transfer'
  scpFirst:
    description: 'Whether to execute scp first. default false'
    type: boolean
    default: false

runs:
  using: node20
  main: dist/index.js
